### ISSUE TITLE
Simplify name to "Early Warning System"

### ISSUE THREAD

**Issue by jgaehring** [runrig-coop/early-warning-system#17]
I've been linking and referring to this project now in various places and realizing it's probably best not to keep referring to this as the "RGO Early Warning System" since we don't want to discourage the potential usefulness of the EWS in other contexts, even if we're deliberately catering this to RGO's specific use case right now.

We can rename this repo from `rgo-early-warning-system` to `early-warning-system` and GH will create redirects to the latter automatically, but I figure better to do this sooner rather than later, before the convention bleeds into other domains and references. Should be safe'n'easy to change the `package.json` and other config files for now too.

**Comment by jgaehring** [comment]
Should Firkin be the new name for this app, @pterygaphykion?

**Comment by jgaehring** [comment]
I can't quite bring myself to commit to Firkin, but I am going to lop off the `rgo-` portion of the name for the reasons above. We can always shorten and/or simplify it further in the future, if for instance we choose to broaden the scope of this tool like I suggested in the #20 discussion on using the system tray.

For more context, the [firkin](https://en.wikipedia.org/wiki/Firkin_(unit)) is the unit of mass measure in the [FFF System](https://en.wikipedia.org/wiki/FFF_system), with the [furlong](https://en.wikipedia.org/wiki/Furlong#History) for distance and the [fortnight](https://en.wikipedia.org/wiki/FFF_system) (or [microfortnight](https://en.wikipedia.org/wiki/FFF_system#Notable_multiples_and_derived_units)) for time. @Wright4TheJob suggested one of those after I proposed assigning random names to projects based on the units for measuring area in the old [open field systems](https://en.wikipedia.org/wiki/Open-field_system), such as the Scottish [runrig](https://en.wikipedia.org/wiki/Run_rig). For instance, the furlong, [chain](https://en.wikipedia.org/wiki/Chain_(unit)), [acre](https://en.wikipedia.org/wiki/Acre#Historical_origin) and [oxgang](https://en.wikipedia.org/wiki/Oxgang), as well as [selion](https://en.wikipedia.org/wiki/Selion), although that wasn't so much a unit of measure as an allotment of land stewarded by one peasant family. Maybe this would make for a fun no-code exercise in the future, to create a list of such names we can pull from in the future.

I'll close this issue after I make the change. GitHub should automatically redirect anyone who comes to the old url in a browser, as well as push/pull commands to this remote via the git CLI. But if anyone wants to update the url in git just for good measure, you can run one of the following:

```sh
git remote set-url origin git@github.com:runrig-coop/early-warning-system.git      # for SSH
git remote set-url origin https://github.com/runrig-coop/early-warning-system.git  # for HTTPS
```

If you're not sure how your remotes are named or what url you have them set to currently, `git remote -v` will list them out.

**Comment by Wright4TheJob** [comment]
Sounds good to me, please proceed!
