### ISSUE TITLE
Add a contribution guide

### ISSUE THREAD

**Issue by pterygaphykion** [runrig-coop/early-warning-system#4]
Add a guide to lay out how to contribute to this project.

**Comment by jgaehring** [comment]
Bumping this to milestone 2 for now.

**Comment by jgaehring** [comment]
I tried setting up a short contrib guide as a [community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file) in the runrig-coop org's [.github](https://github.com/runrig.org/.github) repo, but forgot it won't show up here b/c we already have our own .github directory for this repo. Strangely it did show up in our [Community Standards](https://github.com/runrig-coop/early-warning-system/community). Anyway, I just copy-n-pasted it for now, and doesn't hurt to have the community health file set up too.

As I noted in a hidden comment in both of those CONTRIBUTING markdown files:

>    TODO: Add a more thorough CONTRIBUTING guide based on The Good Docs
>    Project. They have templates, guides and examples, listed below:
>    - https://thegooddocsproject.dev/
>    - https://gitlab.com/tgdp/templates/-/blob/v1.1.0/contributing-guide/guide-contributing-guide.md
>    - https://gitlab.com/tgdp/templates/-/blob/v1.1.0/contributing-guide/template-contributing-guide.md

That seems like plenty for now.
